"""Self-protection: LIDRA must never block its own way off the network.

docs/PRODUCTION_READINESS.md section 2.3 F4 says: *block an IP that is the
operator's own gateway/DNS — expects a refusal via the ``own_ips`` guard —
test it, do not assume.*  When that line was written the guard existed only in
``FirewallManager.bridge_block_ip()`` (bridge mode), so the local/laptop paths
— ``lidra block``, the TUI command bar, the IPC socket — would happily drop the
default route. Blocking your own resolver is a self-inflicted outage and
exactly the failure class that makes an operator uninstall an IDS for good.

These tests cover the parsing that feeds the protected set, the firewall entry
points (local and bridge), and the two operator surfaces.
"""

import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

GATEWAY = "192.168.1.1"
OWN_IP = "192.168.1.7"
RESOLVER = "203.0.113.53"  # TEST-NET-3: cannot collide with a real address
EXTERNAL = "1.2.3.4"


@pytest.fixture
def protected(monkeypatch):
    """Pin the protected set so these tests do not depend on this machine."""
    import response.firewall as fw
    known = frozenset({GATEWAY, OWN_IP, RESOLVER})
    monkeypatch.setattr(fw, "_protected_ips", lambda: known)
    return known


@pytest.fixture(autouse=True)
def _clear_cache():
    """Keep the module-level protected-IP cache from leaking between tests."""
    from utils import interface
    interface.invalidate_protected_ips_cache()
    yield
    interface.invalidate_protected_ips_cache()


def _make_fw(dry_run=True):
    from response.firewall import FirewallManager
    return FirewallManager(backend="iptables", dry_run=dry_run, config={})


class _StubFirewall:
    """A firewall that records nothing and reports success.

    Used to exercise the CLI command logic without touching iptables or nft.
    """

    def __init__(self, dry_run=True, result=True):
        self.dry_run = dry_run
        self._result = result

    def block_ip(self, ip, ttl_seconds=0):
        return self._result

    def unblock_ip(self, ip):
        return self._result


# --- the inputs to the protected set ----------------------------------------

class TestAddressParsing:
    # The real /proc/net/route shape from this machine (Kali, wlan0).
    ROUTE = (
        "Iface\tDestination\tGateway \tFlags\tRefCnt\tUse\tMetric\tMask\t\tMTU\tWindow\tIRTT\n"
        "wlan0\t00000000\t0101A8C0\t0003\t0\t0\t600\t00000000\t0\t0\t0\n"
        "wlan0\t0001A8C0\t00000000\t0001\t0\t0\t600\t00FFFFFF\t0\t0\t0\n"
    )

    def _route(self, tmp_path, text):
        path = tmp_path / "route"
        path.write_text(text)
        return str(path)

    def test_parses_the_default_route_gateway(self, tmp_path):
        from utils.interface import default_gateway
        assert default_gateway(self._route(tmp_path, self.ROUTE)) == GATEWAY

    def test_no_default_route_is_not_an_error(self, tmp_path):
        from utils.interface import default_gateway
        text = "Iface\tDestination\tGateway\nwlan0\t0001A8C0\t00000000\t0001\n"
        assert default_gateway(self._route(tmp_path, text)) == ""

    def test_on_link_zero_gateway_is_skipped(self, tmp_path):
        """A 0.0.0.0 gateway is an on-link route, not a next hop."""
        from utils.interface import default_gateway
        text = "Iface\tDestination\tGateway\nwlan0\t00000000\t00000000\t0001\n"
        assert default_gateway(self._route(tmp_path, text)) == ""

    def test_missing_file_is_not_an_error(self, tmp_path):
        from utils.interface import default_gateway
        assert default_gateway(str(tmp_path / "absent")) == ""

    def test_resolv_conf_keeps_ipv4_and_drops_ipv6(self, tmp_path):
        from utils.interface import dns_servers
        path = tmp_path / "resolv.conf"
        path.write_text(
            "# Generated by NetworkManager\n"
            "search domain.name\n"
            f"nameserver {GATEWAY}   # inline comment\n"
            "nameserver 2401:4900:50:9::7bd\n"
            f"nameserver {RESOLVER}\n"
            f"nameserver {GATEWAY}\n"  # duplicate
            "nameserver\n"  # malformed
        )
        assert dns_servers(str(path)) == [GATEWAY, RESOLVER]

    def test_missing_resolv_conf_is_not_an_error(self, tmp_path):
        from utils.interface import dns_servers
        assert dns_servers(str(tmp_path / "absent")) == []


class TestProtectedSet:
    def test_includes_own_ip_gateway_and_resolvers(self, monkeypatch):
        from utils import interface
        monkeypatch.setattr(interface, "local_ips",
                            lambda: {OWN_IP, "fe80::1", "2401:4900::1"})
        monkeypatch.setattr(interface, "all_local_ipv4", lambda: set())
        monkeypatch.setattr(interface, "default_gateway", lambda *a, **k: GATEWAY)
        monkeypatch.setattr(interface, "dns_servers", lambda *a, **k: [RESOLVER])
        assert interface.protected_ips() == frozenset({OWN_IP, GATEWAY, RESOLVER})

    def test_secondary_interface_addresses_are_protected(self, monkeypatch):
        """A host's *other* addresses must be protected too.

        `local_ips()` returns only the primary egress address, so on a box with
        a second NIC/VLAN/alias the F4 guard used to miss them — measured in the
        netns harness, where `10.88.0.1` on a veth was absent from `local_ips()`
        and `lidra block 10.88.0.1` was allowed."""
        from utils import interface
        monkeypatch.setattr(interface, "local_ips", lambda: {OWN_IP})
        monkeypatch.setattr(interface, "all_local_ipv4",
                            lambda: {"10.44.0.1", "192.0.2.7"})
        monkeypatch.setattr(interface, "default_gateway", lambda *a, **k: "")
        monkeypatch.setattr(interface, "dns_servers", lambda *a, **k: [])
        protected = interface.protected_ips()
        assert "10.44.0.1" in protected
        assert "192.0.2.7" in protected

    def test_ipv6_addresses_are_excluded(self, monkeypatch):
        """The firewall writes IPv4 rules; v6 must not look blockable."""
        from utils import interface
        monkeypatch.setattr(interface, "local_ips", lambda: {"fe80::1", "2401:4900::1"})
        monkeypatch.setattr(interface, "all_local_ipv4", lambda: set())
        monkeypatch.setattr(interface, "default_gateway", lambda *a, **k: "")
        monkeypatch.setattr(interface, "dns_servers", lambda *a, **k: [])
        assert interface.protected_ips() == frozenset()

    def test_protected_ips_survives_a_broken_resolver(self, monkeypatch):
        from utils import interface
        monkeypatch.setattr(interface, "local_ips", lambda: {OWN_IP})
        monkeypatch.setattr(interface, "all_local_ipv4", lambda: set())
        monkeypatch.setattr(interface, "default_gateway", lambda *a, **k: "")
        monkeypatch.setattr(interface, "dns_servers", lambda *a, **k: [])
        assert interface.protected_ips() == frozenset({OWN_IP})

# --- the firewall entry points ----------------------------------------------

class TestBlockRefusesProtected:
    def test_local_block_refuses_the_gateway(self, protected):
        assert _make_fw().block_ip(GATEWAY) is False

    def test_local_block_refuses_this_host(self, protected):
        assert _make_fw().block_ip(OWN_IP) is False

    def test_local_block_refuses_the_resolver(self, protected):
        assert _make_fw().block_ip(RESOLVER) is False

    def test_external_ip_is_still_blockable(self, protected):
        assert _make_fw(dry_run=True).block_ip(EXTERNAL) is True

    def test_refusal_touches_no_firewall_command(self, protected, monkeypatch):
        """The refusal must land before any iptables/nft call is attempted."""
        import response.firewall as fw

        def _forbidden(*args, **kwargs):
            raise AssertionError(f"firewall command attempted: {args}")

        # Build in dry-run (so __init__ probes nothing), then arm it: from here
        # on any subprocess call is the failure under test.
        fwm = _make_fw(dry_run=True)
        fwm.dry_run = False
        monkeypatch.setattr(fw.subprocess, "run", _forbidden)
        assert fwm.block_ip(GATEWAY) is False

    def test_bridge_block_refuses_protected_and_adds_no_rule(self, protected):
        fw = _make_fw(dry_run=False)
        fw.bridge_block_ip(GATEWAY)
        assert GATEWAY not in fw._bridge_blocked

    def test_is_protected_predicate(self, protected):
        from response.firewall import is_protected
        assert is_protected(GATEWAY) is True
        assert is_protected(EXTERNAL) is False
        assert is_protected("") is False
        assert is_protected(None) is False
        assert is_protected(12345) is False

    def test_method_matches_module_predicate(self, protected):
        fw = _make_fw()
        assert fw.is_protected_ip(GATEWAY) is True
        assert fw.is_protected_ip(EXTERNAL) is False

    def test_guard_degrades_quietly_if_the_set_cannot_be_computed(self, monkeypatch):
        """A failure to compute the set must not stop legitimate blocking."""
        import response.firewall as fw
        monkeypatch.setattr(fw, "_protected_ips", lambda: frozenset())
        assert _make_fw().block_ip(EXTERNAL) is True


# --- the operator surfaces --------------------------------------------------

class TestAuditTrail:
    """Plan section 5.9: a security tool that changes firewall state must be
    able to answer "who did that". The audit_log table existed since schema v2
    but nothing wrote to it."""

    def test_log_audit_round_trip(self, tmp_path):
        from database.db import LIDRADatabase

        db = LIDRADatabase(str(tmp_path / "lidra.db"))
        db.log_audit("shiga", "block", "203.0.113.9", "manual", "cli")
        db.log_audit("shiga", "unblock", "203.0.113.9", "", "cli")

        entries = db.get_audit_log()
        assert [e["action"] for e in entries] == ["unblock", "block"]  # newest first
        assert entries[0]["actor"] == "shiga"
        assert entries[1]["target"] == "203.0.113.9"
        assert entries[1]["source"] == "cli"
        assert entries[0]["created_at"]

    def test_audit_survives_missing_fields(self, tmp_path):
        from database.db import LIDRADatabase

        db = LIDRADatabase(str(tmp_path / "lidra.db"))
        db.log_audit("", "block", None, None, None)
        entry = db.get_audit_log()[0]
        assert entry["actor"] == "unknown"
        assert entry["target"] == ""

    def test_get_audit_log_honours_the_limit(self, tmp_path):
        from database.db import LIDRADatabase

        db = LIDRADatabase(str(tmp_path / "lidra.db"))
        for i in range(5):
            db.log_audit("a", "block", f"10.0.0.{i}")
        assert len(db.get_audit_log(2)) == 2

    def test_cli_block_writes_an_audit_row(self, protected, tmp_path, monkeypatch):
        import cli.commands as commands
        from database.db import LIDRADatabase

        db = LIDRADatabase(str(tmp_path / "lidra.db"))
        monkeypatch.setattr(commands, "_open_db", lambda: db)
        monkeypatch.setattr(commands, "_firewall",
                            lambda: _StubFirewall(dry_run=True))
        monkeypatch.setenv("SUDO_USER", "operator")

        assert commands.cmd_block_ip([EXTERNAL, "because"]) is True
        entry = db.get_audit_log()[0]
        assert (entry["actor"], entry["action"], entry["target"]) == (
            "operator", "block", EXTERNAL)
        assert entry["source"] == "cli"
        assert "dry-run" in entry["detail"]

    def test_cli_refusal_is_audited(self, protected, tmp_path, monkeypatch):
        import cli.commands as commands
        from database.db import LIDRADatabase

        db = LIDRADatabase(str(tmp_path / "lidra.db"))
        monkeypatch.setattr(commands, "_open_db", lambda *a, **k: db)
        monkeypatch.setenv("SUDO_USER", "operator")

        assert commands.cmd_block_ip([GATEWAY]) is False
        entry = db.get_audit_log()[0]
        assert entry["action"] == "block_refused"
        assert entry["target"] == GATEWAY

    def test_audit_failure_does_not_break_the_command(self, protected, tmp_path,
                                                      monkeypatch):
        """A missing/broken audit table must not stop an operator blocking."""
        import cli.commands as commands
        from database.db import LIDRADatabase

        db = LIDRADatabase(str(tmp_path / "lidra.db"))
        db._get_connection().execute("DROP TABLE audit_log")
        monkeypatch.setattr(commands, "_open_db", lambda: db)
        monkeypatch.setattr(commands, "_firewall",
                            lambda: _StubFirewall(dry_run=True))
        assert commands.cmd_block_ip([EXTERNAL]) is True

    def test_ipc_audits_the_kernel_reported_peer(self, tmp_path):
        """The IPC path must name the real uid, not a client-supplied string."""
        import getpass
        import socket as _socket
        from database.db import LIDRADatabase
        from tui.ipc_server import TUIIPCServer

        db = LIDRADatabase(str(tmp_path / "lidra.db"))
        server = TUIIPCServer(
            snapshot_fn=lambda: {}, block_fn=lambda ip, reason: None,
            audit_fn=db.log_audit,
        )
        server_sock, client_sock = _socket.socketpair(_socket.AF_UNIX)
        try:
            server._handle_message(
                {"command": "BLOCK", "ip": EXTERNAL, "reason": "tui_block"},
                server_sock,
            )
        finally:
            server_sock.close()
            client_sock.close()

        entry = db.get_audit_log()[0]
        assert entry["action"] == "block"
        assert entry["source"] == "tui-ipc"
        assert entry["actor"] == getpass.getuser()


class TestQueueRuleOwnership:
    """LIDRA must only ever remove the queue rules it can prove it owns.

    The rule used to be untagged, so teardown matched the queue number alone —
    and install/uninstall.sh offered to delete *every* NFQUEUE rule in INPUT.
    A foreign rule on the same queue would have been collateral, and a removed
    queue rule with no consumer is exactly the outage documented in
    docs/SAFE_LINK.md.
    """

    def _fw(self, monkeypatch, listing):
        """Build a firewall whose iptables listing is `listing`; record deletes."""
        import response.firewall as fw

        deletes = []

        class _Result:
            def __init__(self, stdout=""):
                self.stdout = stdout
                self.returncode = 0
                self.stderr = b""

        def _run(argv, **kwargs):
            if argv[:2] == ["iptables", "-L"]:
                return _Result(listing)
            if argv[:2] == ["iptables", "-D"]:
                deletes.append(argv[3])
                return _Result()
            return _Result()

        monkeypatch.setattr(fw.subprocess, "run", _run)
        manager = fw.FirewallManager(backend="iptables", dry_run=True, config={})
        manager.dry_run = False
        return manager, deletes

    TAGGED_LISTING = (
        "Chain INPUT (policy ACCEPT)\n"
        "num  target     prot opt source       destination\n"
        "1    NFQUEUE    tcp  --  0.0.0.0/0    0.0.0.0/0  /* lidra_nfqueue */ NFQUEUE num 0\n"
        "2    NFQUEUE    tcp  --  0.0.0.0/0    0.0.0.0/0  NFQUEUE num 0\n"
        "3    NFQUEUE    udp  --  0.0.0.0/0    0.0.0.0/0  /* someone_else */ NFQUEUE num 0\n"
    )

    def test_only_lidra_tagged_rules_are_removed(self, monkeypatch):
        manager, deletes = self._fw(monkeypatch, self.TAGGED_LISTING)
        manager._flush_local_nfqueue(0)
        assert deletes == ["1"], f"deleted {deletes}, expected only the tagged rule"

    def test_setup_tags_the_rule_it_creates(self, monkeypatch):
        import response.firewall as fw
        from response.firewall import LIDRA_NFQUEUE_COMMENT

        calls = []

        class _Result:
            stdout = ""
            returncode = 0
            stderr = b""

        def _run(argv, **kwargs):
            calls.append(argv)
            return _Result()

        monkeypatch.setattr(fw.subprocess, "run", _run)
        manager = fw.FirewallManager(backend="iptables", dry_run=True, config={})
        manager.dry_run = False
        manager.setup_local_iptables(queue_num=7)

        added = [c for c in calls if c[:3] == ["iptables", "-I", "INPUT"]]
        assert added, "no INPUT rule was added"
        assert LIDRA_NFQUEUE_COMMENT in added[0]
        assert "--queue-bypass" in added[0]

    def test_pretag_install_falls_back_to_the_queue_number(self, monkeypatch):
        """No tagged rules at all -> the queue number is the only handle."""
        listing = (
            "num  target     prot opt source       destination\n"
            "1    NFQUEUE    tcp  --  0.0.0.0/0    0.0.0.0/0  NFQUEUE num 0\n"
            "2    NFQUEUE    tcp  --  0.0.0.0/0    0.0.0.0/0  NFQUEUE num 9\n"
        )
        manager, deletes = self._fw(monkeypatch, listing)
        manager._flush_local_nfqueue(0)
        assert deletes == ["1"], f"deleted {deletes}, queue 9 is not ours to touch"

    def test_deletes_run_in_descending_line_order(self, monkeypatch):
        """Each delete renumbers the rules below it, so order matters."""
        listing = (
            "num  target     prot opt source       destination\n"
            "1    NFQUEUE    tcp  --  0.0.0.0/0    0.0.0.0/0  /* lidra_nfqueue */ NFQUEUE num 0\n"
            "2    ACCEPT     tcp  --  0.0.0.0/0    0.0.0.0/0\n"
            "3    NFQUEUE    tcp  --  0.0.0.0/0    0.0.0.0/0  /* lidra_nfqueue */ NFQUEUE num 0\n"
        )
        manager, deletes = self._fw(monkeypatch, listing)
        manager._flush_local_nfqueue(0)
        assert deletes == ["3", "1"], deletes


def _stub_provider(firewall_result, recorded):
    class _Firewall:
        def block_ip(self, ip, ttl_seconds=0):
            return firewall_result

    class _Provider:
        def block_ip(self, ip, reason=""):
            recorded.append(ip)
            return True

    class _Stub:
        agent = type("A", (), {"firewall": _Firewall()})()
        _data_provider = _Provider()
        _healthy = staticmethod(lambda: True)

    return _Stub()


class TestOperatorPaths:
    def test_cli_block_refuses_and_explains(self, protected, capsys, monkeypatch):
        import cli.commands as commands
        # No database here: the refusal must not write to the live DB (a guard
        # in tests/conftest.py fails the suite if it does).
        monkeypatch.setattr(commands, "_open_db", lambda *a, **k: None)
        assert commands.cmd_block_ip([GATEWAY]) is False
        out = capsys.readouterr().out
        assert "Refusing to block" in out
        assert "off the network" in out

    def test_cli_block_still_accepts_an_external_ip(self, protected, monkeypatch):
        """The guard must not make legitimate targets unblockable.

        Both the firewall and the database are stubbed: a test must never touch
        the host's rules or write a block row into the real detection database.
        """
        import cli.commands as commands

        class _Firewall:
            def __init__(self):
                self.blocked = []

            def block_ip(self, ip, ttl_seconds=0):
                self.blocked.append(ip)
                return True

        fw = _Firewall()
        monkeypatch.setattr(commands, "_firewall", lambda: fw)
        monkeypatch.setattr(commands, "_open_db", lambda: None)

        assert commands.cmd_block_ip([EXTERNAL]) is True
        assert fw.blocked == [EXTERNAL]

    def test_tui_does_not_record_a_refused_block(self, protected):
        """on_block must not write a block row when the firewall refused."""
        from tui.app import LocalProvider
        recorded = []
        LocalProvider.on_block(_stub_provider(False, recorded), GATEWAY)
        assert recorded == []

    def test_tui_records_an_accepted_block(self, protected):
        from tui.app import LocalProvider
        recorded = []
        LocalProvider.on_block(_stub_provider(True, recorded), EXTERNAL)
        assert recorded == [EXTERNAL]


class TestBlockRecordingMatchesReality:
    """`lidra blocks` / `lidra status` must not report a block that is not real.

    Dry-run is the shipped default (``response.dry_run: true``) and means "log
    every detection, never block". ``block_ip`` returns success in dry-run
    without writing a kernel rule, so the DB row must not be marked applied —
    otherwise the status line reports an active block that does not exist.
    """

    def _stub(self, commands, monkeypatch, tmp_path, dry_run):
        from database.db import LIDRADatabase

        db = LIDRADatabase(str(tmp_path / "lidra.db"))

        class _Firewall:
            def block_ip(self, ip, ttl_seconds=0):
                return True

        _Firewall.dry_run = dry_run
        monkeypatch.setattr(commands, "_firewall", _Firewall)
        monkeypatch.setattr(commands, "_open_db", lambda: db)
        return db

    @staticmethod
    def _applied(db, ip):
        row = db._get_connection().execute(
            "SELECT applied FROM blocks WHERE ip_address = ?", (ip,)
        ).fetchone()
        assert row is not None, "the block should still be recorded as evidence"
        return row["applied"]

    def test_dry_run_block_is_recorded_but_not_applied(self, protected, tmp_path,
                                                       monkeypatch):
        import cli.commands as commands
        from response.blocklist import Blocklist

        db = self._stub(commands, monkeypatch, tmp_path, dry_run=True)
        assert commands.cmd_block_ip([EXTERNAL]) is True

        assert self._applied(db, EXTERNAL) == 0
        bl = Blocklist(db)
        bl.sync_from_db()
        assert bl.get_all() == [], "dry-run block counted as an active block"

    def test_live_block_is_marked_applied(self, protected, tmp_path, monkeypatch):
        import cli.commands as commands

        db = self._stub(commands, monkeypatch, tmp_path, dry_run=False)
        assert commands.cmd_block_ip([EXTERNAL]) is True

        assert self._applied(db, EXTERNAL) == 1