/var/log/lidra/*.log {
    daily
    rotate 7
    compress
    missingok
    notifempty
    create 640 root adm
    sharedscripts
    postrotate
        systemctl reload lidra.service >/dev/null 2>&1 || true
    endscript
}
